version: 2

project_name: spm

builds:
  - main: ./cmd/spm/
    binary: spm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - binary

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --bundle=${signature}
      - --yes
      - ${artifact}
    artifacts: checksum

sboms:
  - artifacts: binary

changelog:
  sort: asc
